# Workaround for kind cluster in CI which has no Routes and no PVCs
route:
  enabled: false
upstream:
  postgresql:
    primary:
      persistence:
        enabled: false
  backstage:
    appConfig:
      backend:
        auth:
          keys:
            - secret: sEKIT4CwJ4MwVLzen5SFL6fJmwOPB2sl
